
server:
  port: 8002
  servlet:
    contextPath: /manager

# staff数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_staff?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: employee_staff
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis连接
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml